# Generated by Django 2.2.12 on 2020-05-07 21:27

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserDNI', models.CharField(max_length=20)),
                ('FotoUser', models.ImageField(default='user.png', upload_to='', verbose_name='foto perfil')),
                ('TeleUser', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'datos usuarios',
                'verbose_name_plural': 'informacion',
            },
        ),
        migrations.CreateModel(
            name='HabiUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombHabi', models.CharField(max_length=100)),
                ('DescHabi', ckeditor.fields.RichTextField(default='Estudiante', max_length=2000, verbose_name='Descripcion de la habilidad')),
            ],
            options={
                'verbose_name': 'habilidades de usuario',
                'verbose_name_plural': 'competencias',
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RoleName', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'perfil usuario',
                'verbose_name_plural': 'perfiles',
            },
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Porcentaje', models.DecimalField(decimal_places=1, max_digits=2)),
                ('UdtHabil', models.DateTimeField(auto_now=True)),
                ('IDHabilidades', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.HabiUser')),
                ('IDUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.DatosUser')),
            ],
        ),
        migrations.CreateModel(
            name='DetaRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AddUser', models.DateTimeField(auto_now_add=True)),
                ('UdtUser', models.DateTimeField(auto_now=True)),
                ('EstaRol', models.CharField(max_length=10)),
                ('IDRole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.Roles', verbose_name='Identificador de rol')),
                ('IDUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.DatosUser')),
            ],
        ),
    ]
