# Generated by Django 2.2.12 on 2020-05-14 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0004_auto_20200514_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosuser',
            name='AddData',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='datosuser',
            name='GenUser',
            field=models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino'), ('Otro', 'Otro')], default='Otros', max_length=20, verbose_name='genero'),
        ),
        migrations.AlterField(
            model_name='datosuser',
            name='Modifiat',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de cambios'),
        ),
        migrations.AlterField(
            model_name='detaroles',
            name='AddUser',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha'),
        ),
        migrations.AlterField(
            model_name='detaroles',
            name='EstaRol',
            field=models.CharField(max_length=10, null=True, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='detaroles',
            name='IDUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.DatosUser', verbose_name='identificador de usuaio'),
        ),
        migrations.AlterField(
            model_name='detaroles',
            name='UdtUser',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de actualizacion de usuario'),
        ),
        migrations.AlterField(
            model_name='habiuser',
            name='NombHabi',
            field=models.CharField(max_length=100, null=True, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='rates',
            name='IDHabilidades',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.HabiUser', verbose_name='Identificador de habilidad'),
        ),
        migrations.AlterField(
            model_name='rates',
            name='IDUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.DatosUser', verbose_name='Identificador de usuario'),
        ),
        migrations.AlterField(
            model_name='rates',
            name='Porcentaje',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True, verbose_name='porcentaje'),
        ),
        migrations.AlterField(
            model_name='rates',
            name='UdtHabil',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de actualizacion habilidad'),
        ),
        migrations.AlterField(
            model_name='roles',
            name='RoleName',
            field=models.CharField(max_length=50, verbose_name='nombre'),
        ),
    ]
