# Generated by Django 2.2.12 on 2020-05-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0006_auto_20200514_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosuser',
            name='FotoUser',
            field=models.ImageField(default='user.png', upload_to='perfiles', verbose_name='foto perfil'),
        ),
    ]
