# Generated by Django 2.2.12 on 2020-05-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0007_auto_20200521_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosuser',
            name='FotoUser',
            field=models.ImageField(default='user.png', upload_to='img/perfiles', verbose_name='foto perfil'),
        ),
    ]
