# Generated by Django 2.2.12 on 2020-05-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategProye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lenguaje', models.CharField(max_length=150)),
                ('MotorDB', models.CharField(max_length=150)),
                ('Arquitectura', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'datos proyecto',
                'verbose_name_plural': 'Arquitectura',
            },
        ),
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDTipoDocu', models.CharField(max_length=20)),
                ('IDProyectos', models.CharField(max_length=20)),
                ('IDusuaio', models.CharField(max_length=20)),
                ('NombDoc', models.CharField(max_length=100)),
                ('PathDoc', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Documentos',
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IDCategProye', models.CharField(max_length=20)),
                ('NombProye', models.CharField(max_length=200, null=True, verbose_name='nombre proyecto')),
                ('DescProye', models.CharField(max_length=200, null=True, verbose_name='descripcion proyecto')),
                ('ImgProye', models.ImageField(default='proye.png', upload_to='', verbose_name='imagen proyecto')),
                ('FechaIni', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de inicio')),
                ('FechaFin', models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de finalizacion')),
                ('UrlRepo', models.CharField(max_length=200, null=True, verbose_name='repositorio')),
                ('EstaProye', models.CharField(max_length=200, null=True, verbose_name='estado')),
            ],
            options={
                'verbose_name': 'datos del proyecto',
                'verbose_name_plural': 'informacion',
            },
        ),
        migrations.CreateModel(
            name='TipoDocu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombTipoDoc', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo documento',
                'verbose_name_plural': 'Tipo documento',
            },
        ),
    ]
