# Generated by Django 2.2.12 on 2020-05-14 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='IDProyectos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.Proyectos', verbose_name='Identificador de proyecto'),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='IDTipoDocu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.TipoDocu', verbose_name='Identificador de tipo de documento'),
        ),
        migrations.AlterField(
            model_name='documentos',
            name='IDusuaio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdata.DatosUser', verbose_name='Identificador de usuario'),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='IDCategProye',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.CategProye', verbose_name='Identificador de categoria'),
        ),
    ]
